### ISSUE TITLE
How to create a dataset

### ISSUE THREAD

**Issue by JJGNB** [XunpengYi/EMS#1]
感谢作者的工作！我想知道如何制作自己的数据集，可以使用哪些算法去合成雾天和雨天的图像呢？您可以为我提供一些思路吗，感谢！

**Comment by XunpengYi** [comment]
我们会和EMS-full一同发布对应的合成方法，感谢您的耐心等待。

**Comment by JJGNB** [comment]
> 我们会和EMS-full一同发布对应的合成方法，感谢您的耐心等待。

好的，我已经尝试过使用DPT生成深度图＋HeavyRainRemoval提供的合成方法。期待作者的后续完善工作！
